Repository Team-ESG/BackEnd, pull requests merged in 2023-04, with the labels that each got.

#14 Feat/#9_회원가입
  esg/build.gradle
  esg/src/main/java/esgback/esg/Config/WebsecurityConfig.java
  esg/src/main/java/esgback/esg/Controller/Member/MemberJoinController.java
  esg/src/main/java/esgback/esg/DTO/MemberJoinDto.java
  esg/src/main/java/esgback/esg/Domain/Member/Address.java
  esg/src/main/java/esgback/esg/Domain/Member/Member.java
  esg/src/main/java/esgback/esg/Domain/Member/Role.java
  esg/src/main/java/esgback/esg/Repository/MemberRepository.java
  esg/src/main/java/esgback/esg/Service/Member/MemberJoinService.java
  esg/src/main/resources/data.sql
  esg/src/test/java/esgback/esg/Service/Member/MemberJoinServiceTest.java
Labels: BE

#16 Feat#15
  esg/.gitignore
  esg/build.gradle
  esg/src/main/java/esgback/esg/Controller/Config/WebSecurityConfig.java
  esg/src/main/java/esgback/esg/Controller/Member/MemberJoinController.java
  esg/src/main/java/esgback/esg/Service/Member/MessageService.java
  esg/src/main/resources/application.yml
  esg/src/test/java/esgback/esg/Service/Member/MessageServiceTest.java
Labels: BE

#27 Bug/#1 가게 관련 버그 수정 및 Purchase Domain 삭제
  esg/src/main/java/esgback/esg/DTO/Market/MarketDto.java
  esg/src/main/java/esgback/esg/Domain/Item/Item.java
  esg/src/main/java/esgback/esg/Domain/Market/Market.java
  esg/src/main/java/esgback/esg/Domain/Purchase/Purchase.java
  esg/src/main/java/esgback/esg/Domain/Purchase/PurchaseItem.java
  esg/src/main/java/esgback/esg/Service/Market/MarketService.java
  esg/src/main/resources/data.sql
Labels: bug, BE

#28 Feat#22
  esg/build.gradle
  esg/src/main/java/esgback/esg/Config/RedisConfig.java
  esg/src/main/java/esgback/esg/Config/WebSecurityConfig.java
  esg/src/main/java/esgback/esg/Controller/Member/MemberInfoController.java
  esg/src/main/java/esgback/esg/Controller/Member/MemberJoinController.java
  esg/src/main/java/esgback/esg/DTO/Code/CodeRequestDto.java
  esg/src/main/java/esgback/esg/DTO/Code/CodeResponseDto.java
  esg/src/main/java/esgback/esg/DTO/Code/PwdCodeRequestDto.java
  esg/src/main/java/esgback/esg/DTO/Code/ResetDto.java
  esg/src/main/java/esgback/esg/DTO/Member/MemberIdDto.java
  esg/src/main/java/esgback/esg/DTO/Member/MemberJoinDto.java
  esg/src/main/java/esgback/esg/Domain/Member/Member.java
  esg/src/main/java/esgback/esg/Repository/MemberRepository.java
  esg/src/main/java/esgback/esg/Service/Member/MemberInfoService.java
  esg/src/main/java/esgback/esg/Service/Member/MessageService.java
  esg/src/main/resources/application.yml
  esg/src/main/resources/data.sql
  esg/src/test/java/esgback/esg/Repository/MemberRepositoryTest.java
  esg/src/test/java/esgback/esg/Service/Member/MessageServiceTest.java
Labels: BE

#32 Feat#30_로그인 시 jwt 발급
  esg/build.gradle
  esg/src/main/java/esgback/esg/Config/CustomSecurityConfig.java
  esg/src/main/java/esgback/esg/Config/WebConfig.java
  esg/src/main/java/esgback/esg/Config/WebSecurityConfig.java
  esg/src/main/java/esgback/esg/Controller/Member/MemberInfoController.java
  esg/src/main/java/esgback/esg/Controller/Member/MemberJoinController.java
  esg/src/main/java/esgback/esg/DTO/Member/MemberLoadUserDto.java
  esg/src/main/java/esgback/esg/Domain/Member/Member.java
  esg/src/main/java/esgback/esg/Domain/Member/Role.java
  esg/src/main/java/esgback/esg/Exception/AccessTokenException.java
  esg/src/main/java/esgback/esg/Exception/RefreshTokenException.java
  esg/src/main/java/esgback/esg/Repository/MemberRepository.java
  esg/src/main/java/esgback/esg/Security/Filter/AccessTokenCheckFilter.java
  esg/src/main/java/esgback/esg/Security/Filter/LoginFilter.java
  esg/src/main/java/esgback/esg/Security/Filter/RefreshTokenFilter.java
  esg/src/main/java/esgback/esg/Security/TryUserDetailService.java
  esg/src/main/java/esgback/esg/Security/handler/LoginSuccessHandler.java
  esg/src/main/java/esgback/esg/Service/Member/MemberInfoService.java
  esg/src/main/java/esgback/esg/Service/Member/MemberJoinService.java
  esg/src/main/java/esgback/esg/Util/JWTUtil.java
  esg/src/main/resources/data.sql
  esg/src/test/java/esgback/esg/Repository/MemberRepositoryTest.java
  esg/src/test/java/esgback/esg/Util/JWTUtilTest.java
Labels: BE

#34 휴대폰 인증번호 전송, 확인, 아이디 찾기, 비밀번호 찾기 method 변경
  esg/src/main/java/esgback/esg/Controller/Member/MemberInfoController.java
  esg/src/main/java/esgback/esg/Controller/Member/MemberJoinController.java
Labels: BE, fix

#35 Main Branch Merge
  esg/build.gradle
  esg/src/main/java/esgback/esg/Config/CustomSecurityConfig.java
  esg/src/main/java/esgback/esg/Config/WebConfig.java
  esg/src/main/java/esgback/esg/Config/WebSecurityConfig.java
  esg/src/main/java/esgback/esg/Controller/Member/MemberInfoController.java
  esg/src/main/java/esgback/esg/Controller/Member/MemberJoinController.java
  esg/src/main/java/esgback/esg/Controller/Notice/NoticeController.java
  esg/src/main/java/esgback/esg/DTO/Member/MemberLoadUserDto.java
  esg/src/main/java/esgback/esg/DTO/Notice/NoticeDto.java
  esg/src/main/java/esgback/esg/DTO/Notice/SimpleNoticeDto.java
  esg/src/main/java/esgback/esg/Domain/Member/Member.java
  esg/src/main/java/esgback/esg/Domain/Member/Role.java
  esg/src/main/java/esgback/esg/Domain/Notice/Notice.java
  esg/src/main/java/esgback/esg/Domain/Notice/Read.java
  esg/src/main/java/esgback/esg/Exception/AccessTokenException.java
  esg/src/main/java/esgback/esg/Exception/RefreshTokenException.java
  esg/src/main/java/esgback/esg/Repository/MemberRepository.java
  esg/src/main/java/esgback/esg/Repository/NoticeRepository.java
  esg/src/main/java/esgback/esg/Repository/ReadRepository.java
  esg/src/main/java/esgback/esg/Security/Filter/AccessTokenCheckFilter.java
  esg/src/main/java/esgback/esg/Security/Filter/LoginFilter.java
  esg/src/main/java/esgback/esg/Security/Filter/RefreshTokenFilter.java
  esg/src/main/java/esgback/esg/Security/TryUserDetailService.java
  esg/src/main/java/esgback/esg/Security/handler/LoginSuccessHandler.java
  esg/src/main/java/esgback/esg/Service/Member/MemberInfoService.java
  esg/src/main/java/esgback/esg/Service/Member/MemberJoinService.java
  esg/src/main/java/esgback/esg/Service/Notice/NoticeService.java
  esg/src/main/java/esgback/esg/Util/JWTUtil.java
  esg/src/main/resources/data.sql
  esg/src/test/java/esgback/esg/Repository/MemberRepositoryTest.java
  esg/src/test/java/esgback/esg/Service/Notice/ViewNumTest.java
  esg/src/test/java/esgback/esg/Util/JWTUtilTest.java
Labels: BE

#39 닉네임 수정 시 중복확인 로직 추가
  esg/src/main/java/esgback/esg/Controller/Member/MemberInfoController.java
  esg/src/main/java/esgback/esg/Service/Member/MemberInfoService.java
Labels: BE, fix

#41 카카오 로그인 연동
  esg/build.gradle
  esg/src/main/java/esgback/esg/Config/CustomSecurityConfig.java
  esg/src/main/java/esgback/esg/Controller/Member/MemberJoinController.java
  esg/src/main/java/esgback/esg/DTO/Member/MemberLoadUserDto.java
  esg/src/main/java/esgback/esg/DTO/Member/SocialMemberSetDto.java
  esg/src/main/java/esgback/esg/Security/CustomOAuth2UserService.java
  esg/src/main/java/esgback/esg/Security/CustomUserDetailService.java
  esg/src/main/java/esgback/esg/Security/handler/SocialLoginSuccessHandler.java
  esg/src/main/java/esgback/esg/Service/Member/MemberJoinService.java
  esg/src/main/resources/application.yml
  esg/src/main/resources/static/login.html
  esg/src/main/resources/static/refreshTest.html
  esg/src/main/resources/static/tokenCheckFilterTest.html
  esg/src/main/resources/static/tokenLogin.html
Labels: enhancement, BE

#44 소셜 로그인 로직 변경
  esg/src/main/java/esgback/esg/Controller/Member/MemberInfoController.java
  esg/src/main/java/esgback/esg/Controller/Member/MemberJoinController.java
  esg/src/main/java/esgback/esg/DTO/Member/SocialMemberSetDto.java
  esg/src/main/java/esgback/esg/Domain/Member/Member.java
  esg/src/main/java/esgback/esg/Security/CustomOAuth2UserService.java
  esg/src/main/java/esgback/esg/Service/Member/MemberInfoService.java
  esg/src/main/java/esgback/esg/Service/Member/MemberJoinService.java
Labels: BE, fix

#45 로그아웃 기능 생성 & 자동로그인 생성
  esg/src/main/java/esgback/esg/Config/CustomSecurityConfig.java
  esg/src/main/java/esgback/esg/Controller/Member/MemberAuthController.java
  esg/src/main/java/esgback/esg/Controller/Member/MemberInfoController.java
  esg/src/main/java/esgback/esg/Controller/Member/MemberJoinController.java
  esg/src/main/java/esgback/esg/DTO/Member/MemberReturnDto.java
  esg/src/main/java/esgback/esg/Exception/AccessTokenException.java
  esg/src/main/java/esgback/esg/Exception/RefreshTokenException.java
  esg/src/main/java/esgback/esg/Security/Filter/AutoLoginCheckFilter.java
  esg/src/main/java/esgback/esg/Security/Filter/TokenCheckFilter.java
  esg/src/main/java/esgback/esg/Security/handler/LoginSuccessHandler.java
  esg/src/main/java/esgback/esg/Security/handler/SocialLoginSuccessHandler.java
  esg/src/main/java/esgback/esg/Service/Member/MemberAuthService.java
  esg/src/main/java/esgback/esg/Util/JWTUtil.java
  esg/src/main/resources/static/autoLoginTest.html
Labels: enhancement, BE, fix

#50 회원정보 조회 api 생성
  esg/src/main/java/esgback/esg/Controller/Member/MemberInfoController.java
  esg/src/main/java/esgback/esg/Service/Member/MemberInfoService.java
Labels: enhancement, BE

#51 로그인 성공 시 반환 정보 변경
  esg/src/main/java/esgback/esg/Config/CustomSecurityConfig.java
  esg/src/main/java/esgback/esg/Security/handler/LoginSuccessHandler.java
  esg/src/main/resources/static/tokenLogin.html
Labels: BE, fix

#53 장바구니 기능 구현
  esg/src/main/java/esgback/esg/Controller/ShoppingCart/ShoppingCartController.java
  esg/src/main/java/esgback/esg/DTO/ShoppingCartRequestDto.java
  esg/src/main/java/esgback/esg/Domain/Item/Item.java
  esg/src/main/java/esgback/esg/Domain/ShoppingCart/ShoppingCart.java
  esg/src/main/java/esgback/esg/Domain/ShoppingCart/ShoppingCartListedItem.java
  esg/src/main/java/esgback/esg/Domain/ShoppingCart/ShoppingCartReserve.java
  esg/src/main/java/esgback/esg/EsgApplication.java
  esg/src/main/java/esgback/esg/Repository/ShoppingCartListedItemRepository.java
  esg/src/main/java/esgback/esg/Repository/ShoppingCartRepository.java
  esg/src/main/java/esgback/esg/Repository/ShoppingCartReserveRepository.java
  esg/src/main/java/esgback/esg/Service/Item/ItemService.java
  esg/src/main/java/esgback/esg/Service/ShoppingCart/ShoppingCartService.java
  esg/src/main/resources/data.sql
Labels: BE

#52 예약 기능 구현
  esg/src/main/java/esgback/esg/Controller/Reserve/ReserveController.java
  esg/src/main/java/esgback/esg/DTO/Reserve/ReserveDetailDto.java
  esg/src/main/java/esgback/esg/DTO/Reserve/SimpleReserveDto.java
  esg/src/main/java/esgback/esg/DTO/Reserve/SuccessReserveDto.java
  esg/src/main/java/esgback/esg/DTO/Reserve/WantReserveDto.java
  esg/src/main/java/esgback/esg/Domain/Enum/ReserveState.java
  esg/src/main/java/esgback/esg/Domain/Item/Item.java
  esg/src/main/java/esgback/esg/Domain/Reserve/Reserve.java
  esg/src/main/java/esgback/esg/Domain/Reserve/ReservedItem.java
  esg/src/main/java/esgback/esg/Repository/ReserveRepository.java
  esg/src/main/java/esgback/esg/Service/Item/ItemService.java
  esg/src/main/java/esgback/esg/Service/Member/MemberInfoService.java
  esg/src/main/java/esgback/esg/Service/Reserve/ReserveService.java
  esg/src/test/java/esgback/esg/Service/Reserve/ReserveServiceTest.java
Labels: BE

#56 비밀번호, 닉네임 변경 로직 바꿈
  esg/src/main/java/esgback/esg/Controller/Member/MemberInfoController.java
  esg/src/main/java/esgback/esg/DTO/Code/ResetDto.java
  esg/src/main/java/esgback/esg/Service/Member/MemberInfoService.java
Labels: fix
