Repository Team-ESG/BackEnd, pull requests merged in 2023-05, with the labels that each got.

#57 [BE] Fix/예약 기능 테스트 오류 수정 및 로그인 토큰 적용 #55
  esg/src/main/java/esgback/esg/Controller/Notice/NoticeController.java
  esg/src/main/java/esgback/esg/Controller/Reserve/ReserveController.java
  esg/src/main/java/esgback/esg/Controller/ShoppingCart/ShoppingCartController.java
  esg/src/main/java/esgback/esg/DTO/Reserve/ReserveDetailDto.java
  esg/src/main/java/esgback/esg/DTO/Reserve/WantReserveDto.java
  esg/src/main/java/esgback/esg/DTO/ShoppingCartRequestDto.java
  esg/src/main/java/esgback/esg/Domain/Notice/Read.java
  esg/src/main/java/esgback/esg/Domain/Reserve/Reserve.java
  esg/src/main/java/esgback/esg/Domain/ShoppingCart/ShoppingCart.java
  esg/src/main/java/esgback/esg/Repository/ShoppingCartListedItemRepository.java
  esg/src/main/java/esgback/esg/Repository/ShoppingCartRepository.java
  esg/src/main/java/esgback/esg/Security/handler/LoginSuccessHandler.java
  esg/src/main/java/esgback/esg/Service/Notice/NoticeService.java
  esg/src/main/java/esgback/esg/Service/Reserve/ReserveService.java
  esg/src/main/java/esgback/esg/Service/ShoppingCart/ShoppingCartService.java
Labels: bug, BE

#58 [BE] Main Branch Merge
  esg/build.gradle
  esg/src/main/java/esgback/esg/Config/CustomSecurityConfig.java
  esg/src/main/java/esgback/esg/Controller/Member/MemberAuthController.java
  esg/src/main/java/esgback/esg/Controller/Member/MemberInfoController.java
  esg/src/main/java/esgback/esg/Controller/Member/MemberJoinController.java
  esg/src/main/java/esgback/esg/Controller/Notice/NoticeController.java
  esg/src/main/java/esgback/esg/Controller/Reserve/ReserveController.java
  esg/src/main/java/esgback/esg/Controller/ShoppingCart/ShoppingCartController.java
  esg/src/main/java/esgback/esg/DTO/Code/ResetDto.java
  esg/src/main/java/esgback/esg/DTO/Member/MemberJoinDto.java
  esg/src/main/java/esgback/esg/DTO/Member/MemberLoadUserDto.java
  esg/src/main/java/esgback/esg/DTO/Member/MemberReturnDto.java
  esg/src/main/java/esgback/esg/DTO/Reserve/ReserveDetailDto.java
  esg/src/main/java/esgback/esg/DTO/Reserve/SimpleReserveDto.java
  esg/src/main/java/esgback/esg/DTO/Reserve/SuccessReserveDto.java
  esg/src/main/java/esgback/esg/DTO/Reserve/WantReserveDto.java
  esg/src/main/java/esgback/esg/DTO/ShoppingCartRequestDto.java
  esg/src/main/java/esgback/esg/Domain/Enum/ReserveState.java
  esg/src/main/java/esgback/esg/Domain/Item/Item.java
  esg/src/main/java/esgback/esg/Domain/Member/Member.java
  esg/src/main/java/esgback/esg/Domain/Notice/Read.java
  esg/src/main/java/esgback/esg/Domain/Reserve/Reserve.java
  esg/src/main/java/esgback/esg/Domain/Reserve/ReservedItem.java
  esg/src/main/java/esgback/esg/Domain/ShoppingCart/ShoppingCart.java
  esg/src/main/java/esgback/esg/Domain/ShoppingCart/ShoppingCartListedItem.java
  esg/src/main/java/esgback/esg/Domain/ShoppingCart/ShoppingCartReserve.java
  esg/src/main/java/esgback/esg/EsgApplication.java
  esg/src/main/java/esgback/esg/Exception/AccessTokenException.java
  esg/src/main/java/esgback/esg/Exception/RefreshTokenException.java
  esg/src/main/java/esgback/esg/Repository/ReserveRepository.java
  esg/src/main/java/esgback/esg/Repository/ShoppingCartListedItemRepository.java
  esg/src/main/java/esgback/esg/Repository/ShoppingCartRepository.java
  esg/src/main/java/esgback/esg/Repository/ShoppingCartReserveRepository.java
  esg/src/main/java/esgback/esg/Security/CustomOAuth2UserService.java
  esg/src/main/java/esgback/esg/Security/CustomUserDetailService.java
  esg/src/main/java/esgback/esg/Security/Filter/AutoLoginCheckFilter.java
  esg/src/main/java/esgback/esg/Security/Filter/TokenCheckFilter.java
  esg/src/main/java/esgback/esg/Security/handler/LoginSuccessHandler.java
  esg/src/main/java/esgback/esg/Security/handler/SocialLoginSuccessHandler.java
  esg/src/main/java/esgback/esg/Service/Item/ItemService.java
  esg/src/main/java/esgback/esg/Service/Member/MemberAuthService.java
  esg/src/main/java/esgback/esg/Service/Member/MemberInfoService.java
  esg/src/main/java/esgback/esg/Service/Member/MemberJoinService.java
  esg/src/main/java/esgback/esg/Service/Notice/NoticeService.java
  esg/src/main/java/esgback/esg/Service/Reserve/ReserveService.java
  esg/src/main/java/esgback/esg/Service/ShoppingCart/ShoppingCartService.java
  esg/src/main/java/esgback/esg/Util/JWTUtil.java
  esg/src/main/resources/application.yml
  esg/src/main/resources/data.sql
  esg/src/main/resources/static/autoLoginTest.html
  esg/src/main/resources/static/login.html
  esg/src/main/resources/static/tokenCheckFilterTest.html
  esg/src/main/resources/static/tokenLogin.html
  esg/src/test/java/esgback/esg/Service/Reserve/ReserveServiceTest.java
Labels: BE

#64 feat/찜 기능
  esg/src/main/java/esgback/esg/Controller/Wish/WishController.java
  esg/src/main/java/esgback/esg/DTO/Market/SimpleMarketDto.java
  esg/src/main/java/esgback/esg/Domain/Market/Market.java
  esg/src/main/java/esgback/esg/Domain/Wish/Wish.java
  esg/src/main/java/esgback/esg/Domain/Wish/WishedMarket.java
  esg/src/main/java/esgback/esg/Repository/WishRepository.java
  esg/src/main/java/esgback/esg/Service/Wish/WishService.java
Labels: BE

#63 Fix/shopping cart
  esg/src/main/java/esgback/esg/Controller/ShoppingCart/ShoppingCartController.java
  esg/src/main/java/esgback/esg/DTO/ShoppingCart/ShoppingCartListedItemDto.java
  esg/src/main/java/esgback/esg/DTO/ShoppingCart/ShoppingCartRequestDto.java
  esg/src/main/java/esgback/esg/Domain/ShoppingCart/ShoppingCartListedItem.java
  esg/src/main/java/esgback/esg/Domain/ShoppingCart/ShoppingCartReserve.java
  esg/src/main/java/esgback/esg/Repository/ShoppingCartListedItemRepository.java
  esg/src/main/java/esgback/esg/Repository/ShoppingCartReserveRepository.java
  esg/src/main/java/esgback/esg/Service/ShoppingCart/ShoppingCartService.java
Labels: enhancement, BE

#65 소셜 로그인 시 회원가입 로직 변경
  esg/src/main/java/esgback/esg/Config/CustomSecurityConfig.java
  esg/src/main/java/esgback/esg/DTO/Member/MemberLoadUserDto.java
  esg/src/main/java/esgback/esg/DTO/Member/MemberSocialJoinDto.java
  esg/src/main/java/esgback/esg/Security/CustomOAuth2UserService.java
  esg/src/main/java/esgback/esg/Security/CustomUserDetailService.java
  esg/src/main/java/esgback/esg/Security/handler/SocialLoginSuccessHandler.java
  esg/src/test/java/esgback/esg/Service/Notice/ViewNumTest.java
Labels: BE, fix

#66 Feat/search
  esg/src/main/java/esgback/esg/Controller/Search/SearchController.java
  esg/src/main/java/esgback/esg/Repository/ItemRepository.java
  esg/src/main/java/esgback/esg/Repository/MarketRepository.java
  esg/src/main/java/esgback/esg/Service/Search/SearchService.java
  esg/src/main/resources/application.yml
Labels: BE

#68 fix/상품 리스트 DTO 수정
  esg/src/main/java/esgback/esg/Controller/Item/ItemController.java
  esg/src/main/java/esgback/esg/DTO/Item/SimpleItemDto.java
  esg/src/main/java/esgback/esg/Service/Search/SearchService.java
Labels: BE, fix

#71 fix/새로운 비밀번호로 로그인 시 성공 완료하게 변경
  esg/src/main/java/esgback/esg/Service/Member/MemberInfoService.java
Labels: BE, fix

#73 로그인 시 반환 정보 변경
  esg/src/main/java/esgback/esg/Config/CustomSecurityConfig.java
  esg/src/main/java/esgback/esg/DTO/Member/MemberReturnDto.java
  esg/src/main/java/esgback/esg/Security/handler/LoginSuccessHandler.java
  esg/src/main/java/esgback/esg/Security/handler/SocialLoginSuccessHandler.java
Labels: BE, fix

#75 자동로그인 할 때, response 변경
  esg/src/main/java/esgback/esg/Config/CustomSecurityConfig.java
  esg/src/main/java/esgback/esg/Security/Filter/AutoLoginCheckFilter.java
Labels: BE, fix

#76 main 머지
  esg/src/main/java/esgback/esg/Config/CustomSecurityConfig.java
  esg/src/main/java/esgback/esg/Controller/Item/ItemController.java
  esg/src/main/java/esgback/esg/Controller/Market/MarketController.java
  esg/src/main/java/esgback/esg/Controller/Member/MemberInfoController.java
  esg/src/main/java/esgback/esg/Controller/Reserve/ReserveController.java
  esg/src/main/java/esgback/esg/Controller/Search/SearchController.java
  esg/src/main/java/esgback/esg/Controller/ShoppingCart/ShoppingCartController.java
  esg/src/main/java/esgback/esg/Controller/Wish/WishController.java
  esg/src/main/java/esgback/esg/DTO/Item/ItemDto.java
  esg/src/main/java/esgback/esg/DTO/Item/SimpleItemDto.java
  esg/src/main/java/esgback/esg/DTO/Market/MarketDto.java
  esg/src/main/java/esgback/esg/DTO/Market/SimpleMarketDto.java
  esg/src/main/java/esgback/esg/DTO/Member/MemberLoadUserDto.java
  esg/src/main/java/esgback/esg/DTO/Member/MemberReturnDto.java
  esg/src/main/java/esgback/esg/DTO/Member/MemberSocialJoinDto.java
  esg/src/main/java/esgback/esg/DTO/Reserve/SimpleReserveDto.java
  esg/src/main/java/esgback/esg/DTO/Reserve/WantReserveDto.java
  esg/src/main/java/esgback/esg/DTO/ShoppingCart/ShoppingCartListedItemDto.java
  esg/src/main/java/esgback/esg/DTO/ShoppingCart/ShoppingCartRequestDto.java
  esg/src/main/java/esgback/esg/Domain/Item/Item.java
  esg/src/main/java/esgback/esg/Domain/Market/Market.java
  esg/src/main/java/esgback/esg/Domain/ShoppingCart/ShoppingCartListedItem.java
  esg/src/main/java/esgback/esg/Domain/ShoppingCart/ShoppingCartReserve.java
  esg/src/main/java/esgback/esg/Domain/Wish/Wish.java
  esg/src/main/java/esgback/esg/Domain/Wish/WishedMarket.java
  esg/src/main/java/esgback/esg/Repository/ItemRepository.java
  esg/src/main/java/esgback/esg/Repository/MarketRepository.java
  esg/src/main/java/esgback/esg/Repository/ShoppingCartListedItemRepository.java
  esg/src/main/java/esgback/esg/Repository/ShoppingCartReserveRepository.java
  esg/src/main/java/esgback/esg/Repository/WishRepository.java
  esg/src/main/java/esgback/esg/Security/CustomOAuth2UserService.java
  esg/src/main/java/esgback/esg/Security/CustomUserDetailService.java
  esg/src/main/java/esgback/esg/Security/Filter/AutoLoginCheckFilter.java
  esg/src/main/java/esgback/esg/Security/handler/LoginSuccessHandler.java
  esg/src/main/java/esgback/esg/Security/handler/SocialLoginSuccessHandler.java
  esg/src/main/java/esgback/esg/Service/Item/ItemService.java
  esg/src/main/java/esgback/esg/Service/Market/MarketService.java
  esg/src/main/java/esgback/esg/Service/Member/MemberInfoService.java
  esg/src/main/java/esgback/esg/Service/Reserve/ReserveService.java
  esg/src/main/java/esgback/esg/Service/Search/SearchService.java
  esg/src/main/java/esgback/esg/Service/ShoppingCart/ShoppingCartService.java
  esg/src/main/java/esgback/esg/Service/Wish/WishService.java
  esg/src/main/resources/application.yml
  esg/src/test/java/esgback/esg/Service/Notice/ViewNumTest.java
Labels: BE

#78 Fix/#77
  esg/src/main/java/esgback/esg/Controller/Item/ItemController.java
  esg/src/main/java/esgback/esg/Controller/Reserve/ReserveController.java
  esg/src/main/java/esgback/esg/DTO/Item/ItemDto.java
  esg/src/main/java/esgback/esg/DTO/Item/SimpleItemDto.java
  esg/src/main/java/esgback/esg/DTO/Reserve/ReserveDetailDto.java
  esg/src/main/java/esgback/esg/Domain/Reserve/Reserve.java
  esg/src/main/java/esgback/esg/Repository/ItemRepository.java
  esg/src/main/java/esgback/esg/Service/Item/ItemService.java
  esg/src/main/java/esgback/esg/Service/Reserve/ReserveService.java
  esg/src/main/java/esgback/esg/Service/Search/SearchService.java
Labels: BE, fix

#79 fix/예약 완료 시 멤버 총 할인 금액 추가
  esg/src/main/java/esgback/esg/Domain/Member/Member.java
  esg/src/main/java/esgback/esg/Service/Reserve/ReserveService.java
Labels: BE, fix

#81 kakao 철자 틀림 수정
  esg/src/main/java/esgback/esg/Security/handler/SocialLoginSuccessHandler.java
Labels: BE, fix

#83 fix/빌드 오류 수정
  esg/src/main/java/esgback/esg/Controller/Reserve/ReserveController.java
Labels: bug, BE

#84 로그인 리스폰스 변경
  esg/src/main/java/esgback/esg/DTO/Member/MemberReturnDto.java
  esg/src/main/java/esgback/esg/Security/Filter/AutoLoginCheckFilter.java
  esg/src/main/java/esgback/esg/Security/handler/LoginSuccessHandler.java
  esg/src/main/java/esgback/esg/Security/handler/SocialLoginSuccessHandler.java
Labels: BE, fix

#86 response data json으로 변경
  esg/src/main/java/esgback/esg/Security/handler/SocialLoginSuccessHandler.java
Labels: BE, fix

#91 [BE] 장바구니 관련 버그 수정
  esg/src/main/java/esgback/esg/Controller/Reserve/ReserveController.java
  esg/src/main/java/esgback/esg/Controller/ShoppingCart/ShoppingCartController.java
  esg/src/main/java/esgback/esg/Service/ShoppingCart/ShoppingCartService.java
Labels: bug, BE

#94 서버 연동
  esg/build.gradle
  esg/src/main/java/esgback/esg/Domain/Notice/Reader.java
  esg/src/main/java/esgback/esg/Repository/ReadRepository.java
  esg/src/main/java/esgback/esg/Service/Notice/NoticeService.java
  esg/src/main/resources/application.yml
  esg/src/test/java/esgback/esg/Service/Member/MessageServiceTest.java
  esg/src/test/java/esgback/esg/Service/Notice/ViewNumTest.java
  esg/src/test/java/esgback/esg/Service/Reserve/ReserveServiceTest.java
Labels: enhancement, BE

#96 Feat#87
  esg/build.gradle
  esg/src/main/java/esgback/esg/Config/S3Config.java
  esg/src/main/java/esgback/esg/Controller/File/FileUploadController.java
  esg/src/main/java/esgback/esg/Domain/Item/Item.java
  esg/src/main/java/esgback/esg/Domain/Market/Market.java
  esg/src/main/java/esgback/esg/Util/S3Util.java
  esg/src/main/resources/application.yml
Labels: enhancement, BE

#97 fix/entity 생성 오류 수정
  esg/src/main/java/esgback/esg/Domain/ShoppingCart/ShoppingCartListedItem.java
  esg/src/main/java/esgback/esg/Service/ShoppingCart/ShoppingCartService.java
Labels: bug, BE

#100 프론트엔드 요청 사항 수정
  src/main/java/esgback/esg/Controller/File/FileUploadController.java
  src/main/java/esgback/esg/DTO/Market/MarketReturnDto.java
  src/main/java/esgback/esg/Security/handler/LoginSuccessHandler.java
  src/main/java/esgback/esg/Util/S3Util.java
  src/main/resources/data.sql
Labels: BE, fix
